### ISSUE TITLE
[Bug] KEES Experiments Fail to Start

### ISSUE THREAD

**Issue by ignatzami** [mwerle/OrbitalMaterialScience#46]
Ran into two possibly related issues:

1) Have a contract where I need to run the Passive Exposure scan while landed at Kerbin. Launched a ship, attached the plate, and experiment. Started the experiment. Hit 100x and waited for ~10 days in game. Exposure stayed at 0.0

2) Recovered, and re-launched. Setup the plate, and experiment. Hit "Start Experiment" the plate unfolded but the "Start Experiment" button stayed, and the exposure bar never appeared.

**Comment by ignatzami** [comment]
Currently running v.0.8.1 through CKAN

**Comment by killwort** [comment]
I'm experiencing the same problem. Experiment starts and deploys, button resets back to "start experiment" immediately after deployment. Exposure stays at 0.0.

KSP1.7.3.2594, NEOS 0.8.1 installed via CKAN.

Installed mod list [mods.ckan.zip](https://github.com/mwerle/OrbitalMaterialScience/files/3414927/mods.ckan.zip)

Save folder [KSX.zip](https://github.com/mwerle/OrbitalMaterialScience/files/3414934/KSX.zip) - the only vessel in orbit has PEC and experiments attached ready to debug.

Log file [KSP.log](https://github.com/mwerle/OrbitalMaterialScience/files/3414939/KSP.log)

Looks like the problem is caused by the absence of kerbal alarm clock.

**Comment by killwort** [comment]
I've installed latest KAC (for KSP 1.6) and now my experiments work normally.
This can be counted as a workaround, although NEOS shouldn't fail without KAC installed :)

**Comment by mwerle** [comment]
Sorry!  For some reason I didn't get notified of this issue.

Thanks so much for the analysis and logs etc (nobody on the forum could be arsed).  Now I can fix it.

**Comment by mwerle** [comment]
Fixed; sorry it took so long, been so busy with real life.
The log showed the issue immediately so thanks for that.
